const fs = require('fs');
const path = require('path');

const rootDir = __dirname;
const toolsDir = path.join(rootDir, 'js', 'tools');

// 1. Read utils.js and strip export keywords
let utilsCode = fs.readFileSync(path.join(toolsDir, 'utils.js'), 'utf8');
utilsCode = utilsCode.replace(/export function /g, 'function ')
                     .replace(/export const /g, 'const ')
                     .replace(/export let /g, 'let ');

// 2. The 20 tools in exact user-specified order
const toolsList = [
    // 1. ✍️ 文字與格式 (6 款)
    { file: 'textCompare.js', name: 'textCompareTool' },
    { file: 'jsonFormatter.js', name: 'jsonFormatterTool' },
    { file: 'wordCounter.js', name: 'wordCounterTool' },
    { file: 'caseConverter.js', name: 'caseConverterTool' },
    { file: 'textDedup.js', name: 'textDedupTool' },
    { file: 'markdownEditor.js', name: 'markdownEditorTool' },

    // 2. 🔐 安全與開發 (6 款)
    { file: 'jweHelper.js', name: 'jweHelperTool' },
    { file: 'companyCrypto.js', name: 'companyCryptoTool' },
    { file: 'hashGenerator.js', name: 'hashGeneratorTool' },
    { file: 'base64Codec.js', name: 'base64CodecTool' },
    { file: 'urlCodec.js', name: 'urlCodecTool' },
    { file: 'regexTester.js', name: 'regexTesterTool' },

    // 3. 🛠️ 實用與生活 (6 款)
    { file: 'currencyConverter.js', name: 'currencyConverterTool' },
    { file: 'dateCalculator.js', name: 'dateCalculatorTool' },
    { file: 'converterBox.js', name: 'converterBoxTool' },
    { file: 'colorTools.js', name: 'colorToolsTool' },
    { file: 'luckyWheel.js', name: 'luckyWheelTool' },
    { file: 'qrGenerator.js', name: 'qrGeneratorTool' },

    // 4. 🌐 網路與查詢 (2 款)
    { file: 'httpStatus.js', name: 'httpStatusTool' },
    { file: 'mimeType.js', name: 'mimeTypeTool' }
];

let toolsCode = '';
for (const tool of toolsList) {
    const filePath = path.join(toolsDir, tool.file);
    if (!fs.existsSync(filePath)) {
        console.error('File not found: ' + filePath);
        process.exit(1);
    }
    let code = fs.readFileSync(filePath, 'utf8');
    // strip import statements
    code = code.replace(/import\s+[\s\S]*?from\s+['"][^'"]+['"];?/g, '');
    // replace export const <name> = with const <name> =
    code = code.replace(new RegExp(`export\\s+const\\s+${tool.name}\\s*=`), `const ${tool.name} =`);

    // wrap in an IIFE for clean variable scope isolation
    toolsCode += `
// ==========================================
// Tool: ${tool.name} (${tool.file})
// ==========================================
const ${tool.name} = (function() {
${code}
return ${tool.name};
})();
`;
}

// 3. toolsConfig definition
const toolsConfigCode = `
// ==========================================
// Tools Configuration (Scheme A Order)
// ==========================================
const toolsConfig = [
${toolsList.map(t => '    ' + t.name).join(',\n')}
];
`;

// 4. app.js
let appCode = fs.readFileSync(path.join(rootDir, 'js', 'app.js'), 'utf8');
appCode = appCode.replace(/import\s+[\s\S]*?from\s+['"][^'"]+['"];?/g, '');

// 5. Assemble bundle
const bundleContent = `/**
 * ShengTools - All-in-One Standalone Bundle
 * Compatible with file:// direct click & offline local use.
 * Auto-generated by build.js.
 */
(function() {
'use strict';

// --- Shared Utilities ---
${utilsCode}

// --- Tools Modules ---
${toolsCode}

${toolsConfigCode}

// --- Application Core & Routing ---
${appCode}

})();
`;

const outputPath = path.join(rootDir, 'js', 'app.bundle.js');
fs.writeFileSync(outputPath, bundleContent, 'utf8');
console.log('Successfully bundled ShengTools to js/app.bundle.js (' + (bundleContent.length / 1024).toFixed(1) + ' KB)');
